version: 2

models:
  #######################################################################
  # FACT_RATINGS
  #######################################################################

  - name: fct_ratings
    description: "Fact table storing user movie ratings."

    config:
      tags:
        - fact
        - analytics
        - movielens

      meta:
        owner: "Harsh Soni"
        team: "Analytics Engineering"
        source_system: "MovieLens"

    columns:

      - name: user_id
        description: "Foreign key to dim_users"
        tests:
          - not_null

      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_movies')
                field: movie_id

      - name: rating
        description: "Movie Rating"
        tests:
          - not_null

      - name: rating_timestamp
        description: "Timestamp of Rating"
        tests:
          - not_null

  #######################################################################
  # FACT_GENOME_SCORES
  #######################################################################

  - name: fct_genome_scores
    description: "Fact table storing MovieLens genome relevance scores."

    config:
      tags:
        - fact
        - analytics
        - movielens

      meta:
        owner: "Harsh Soni"
        team: "Analytics Engineering"
        source_system: "MovieLens"

    columns:

      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null

      - name: tag_id
        description: "Foreign key to dim_genome_tags"
        tests:
          - not_null

      - name: relevance_score
        description: "Genome relevance score"
        tests:
          - not_null

